version: '3'

services:
  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: node index.js
    volumes:
      - .:/usr/src/app
    tty: true
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:3000"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge